(function() {var implementors = {};
implementors["actix_web"] = [{text:"impl Handler&lt;<a class=\"struct\" href=\"actix_web/client/struct.Connect.html\" title=\"struct actix_web::client::Connect\">Connect</a>&gt; for <a class=\"struct\" href=\"actix_web/client/struct.ClientConnector.html\" title=\"struct actix_web::client::ClientConnector\">ClientConnector</a>",synthetic:false,types:["actix_web::client::connector::ClientConnector"]},{text:"impl&lt;H:&nbsp;<a class=\"trait\" href=\"actix_web/server/trait.IntoHttpHandler.html\" title=\"trait actix_web::server::IntoHttpHandler\">IntoHttpHandler</a>&gt; Handler&lt;Signal&gt; for <a class=\"struct\" href=\"actix_web/struct.HttpServer.html\" title=\"struct actix_web::HttpServer\">HttpServer</a>&lt;H&gt;",synthetic:false,types:["actix_web::server::srv::HttpServer"]},{text:"impl&lt;H:&nbsp;<a class=\"trait\" href=\"actix_web/server/trait.IntoHttpHandler.html\" title=\"trait actix_web::server::IntoHttpHandler\">IntoHttpHandler</a>&gt; Handler&lt;<a class=\"struct\" href=\"actix_web/server/struct.PauseServer.html\" title=\"struct actix_web::server::PauseServer\">PauseServer</a>&gt; for <a class=\"struct\" href=\"actix_web/struct.HttpServer.html\" title=\"struct actix_web::HttpServer\">HttpServer</a>&lt;H&gt;",synthetic:false,types:["actix_web::server::srv::HttpServer"]},{text:"impl&lt;H:&nbsp;<a class=\"trait\" href=\"actix_web/server/trait.IntoHttpHandler.html\" title=\"trait actix_web::server::IntoHttpHandler\">IntoHttpHandler</a>&gt; Handler&lt;<a class=\"struct\" href=\"actix_web/server/struct.ResumeServer.html\" title=\"struct actix_web::server::ResumeServer\">ResumeServer</a>&gt; for <a class=\"struct\" href=\"actix_web/struct.HttpServer.html\" title=\"struct actix_web::HttpServer\">HttpServer</a>&lt;H&gt;",synthetic:false,types:["actix_web::server::srv::HttpServer"]},{text:"impl&lt;H:&nbsp;<a class=\"trait\" href=\"actix_web/server/trait.IntoHttpHandler.html\" title=\"trait actix_web::server::IntoHttpHandler\">IntoHttpHandler</a>&gt; Handler&lt;<a class=\"struct\" href=\"actix_web/server/struct.StopServer.html\" title=\"struct actix_web::server::StopServer\">StopServer</a>&gt; for <a class=\"struct\" href=\"actix_web/struct.HttpServer.html\" title=\"struct actix_web::HttpServer\">HttpServer</a>&lt;H&gt;",synthetic:false,types:["actix_web::server::srv::HttpServer"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
